### PR TITLE
fix(alert): add dompurify to resolve injection problems

### LINKED ISSUE #743: [Component] Alert
### Context

There are `innerHTML` element props in the Alert component that could potentially create security vulnerabilities by allowing scripts to be injected through the `messageTitle` and `messageText` props.

Ref:
https://github.com/juntossomosmais/atomium/blob/2dba7eab8232c2226a3e2f442e816c142d662364/packages/core/src/components/alert/alert.tsx#L66

### Reproduction:

https://github.com/user-attachments/assets/31f01d86-d929-4140-bf07-0a1943494d50

This security issue can be resolved by removing the innerHTML props and instead passing the content as children to the component.

### PR DESCRIPTION
**Pull request by gabrielduete**
[Task](https://juntossomosmais.monday.com/boards/3345740155/views/76424285/pulses/8977054675)

## Summary

Closes #743 

This pull request introduces a new dependency (`dompurify`) to sanitize HTML content and updates the `AtomAlert` component to use it, ensuring safer rendering of user-provided HTML. Additionally, minor reordering of dependencies in `package.json` was performed for consistency.

### Dependency Management:

* Added `dompurify` as a new dependency in `package.json` to provide HTML sanitization functionality. (`[package.jsonL35-R36](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L35-R36)`)
* Reordered entries in `optionalDependencies` within `package.json` for improved consistency. (`[package.jsonL116-R118](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L116-R118)`)

### Security Enhancements:

* Imported `dompurify` in `packages/core/src/components/alert/alert.tsx` to sanitize HTML content. (`[packages/core/src/components/alert/alert.tsxR10](diffhunk://#diff-e93afe864fc2b3aaa845eb7c0d6a03e75223ce1d6c837408789a0471db01d0f5R10)`)
* Updated `AtomAlert` component to sanitize `messageTitle` and `messageText` properties using `DOMPurify.sanitize`, mitigating potential security risks from untrusted HTML. (`[packages/core/src/components/alert/alert.tsxL66-R77](diffhunk://#diff-e93afe864fc2b3aaa845eb7c0d6a03e75223ce1d6c837408789a0471db01d0f5L66-R77)`)

We're implementing a new lib, but we shouldn't have any problems:
- Constant support (last update 2 weeks ago)
- Popular (>500k+ uses)
- Slight impact on bundle (21.5kb)
- No breaking changes

image

## Evidences

Before

https://github.com/user-attachments/assets/530ebb4e-ce02-43a6-92b6-d4c76ced9344

After

https://github.com/user-attachments/assets/b0ab12d6-4182-43a6-975b-fc4ded2ea891

image

### CODE REVIEW

**Review by tassioFront — APPROVED** [review]
🚀

File: packages/core/src/components/alert/alert.tsx [hunk 1]
```diff
@@ -63,10 +64,16 @@ export class AtomAlert {
...
+                    class='atom-title'
+                    innerHTML={DOMPurify.sanitize(this.messageTitle)}
+                  ></div>
                 )}
                 {this.messageText && (
-                  <div class='atom-message' innerHTML={this.messageText}></div>
+                  <div
+                    class='atom-message'
+                    innerHTML={DOMPurify.sanitize(this.messageText)}
+                  ></div>
```
[the remark this answers is not in the document]
Comment (gabrielduete) [reply packages/core/src/components/alert/alert.tsx:76]: Yeah! Made: https://github.com/juntossomosmais/atomium/pull/749/commits/d1b5a804865bdf4cafd2651807201e972534d75c

File: packages/core/src/components/alert/alert.spec.ts [hunk 2]
```diff
@@ -257,4 +260,32 @@ describe('AtomAlert', () => {
 
     expect(spy).toHaveBeenCalled()
   })
+
+  it('should sanitize the messageTitle and messageText using DOMPurify', async () => {
+    const sanitizedText = '<i>Sanitized Text</i>'
+    const sanitizedTitle = '<strong>Sanitized Title</strong>'
+
+    ;(DOMPurify.sanitize as jest.Mock).mockImplementation((input: string) => {
```
Comment (tassioFront) [inline packages/core/src/components/alert/alert.spec.ts:268]: Guess it doesn't help too much, man. Once there is no logic on our side, this test would help more if we don't mock the library.

Comment (gabrielduete) [reply packages/core/src/components/alert/alert.spec.ts]: It is not feasible to test this behavior without using mocks, as DOMPurify performs sanitization at runtime.

Like you said, mocking in this context is not appropriate, as it would essentially mean testing the internal behavior of an external library. Therefore, I decided to remove the tests: https://github.com/juntossomosmais/atomium/pull/749/commits/ae8602de638e6f6bd953d9d265f841b0b0599bb0

I will continue to rely on the robustness of the library itself, especially considering that its test suite is extensive and trustworthy: https://github.com/cure53/DOMPurify/blob/main/test/test-suite.js

File: packages/core/src/components/alert/alert.tsx (hunk 1 above)
[the remark this answers is not in the document]
Comment (gabrielduete) [reply packages/core/src/components/alert/alert.tsx:76]: Update: https://github.com/juntossomosmais/atomium/pull/749#discussion_r2059068604

File: packages/core/src/components/alert/alert.spec.ts (hunk 2 above)
Comment (tassioFront) [reply packages/core/src/components/alert/alert.spec.ts]: It makes sense!

**Review by tassioFront — APPROVED** [review]

**Review by igorwessel — APPROVED** [review]

**Review by felipefialho — APPROVED** [review]
